### PR TITLE
Initial hw2 for Grace Calkins (calkins7)

### PR DESCRIPTION
**Pull request by calkins7**
I messed up the branching again to make a good PR. My file structure is as follows: 
- `dqn.py`: contains the DQN neural network and Experience Replay objects, as well as the functions to optimize the model. 
- `epsilon_greedy.py`: contains the functions to select epsilon greedy actions or random actions
- `get_state_value_function.py`: this function is obsolete and can be ignored. 
- `plotters.py`: functions to plot
- `train_discreteaction_pendulum`: run this file to train DQN.

Thanks for your feedback!
Grace

### CODE REVIEW

**Comment by calkins7** [comment]
Also, my ablation study is not set up fully right now. :)

**Comment by npnike10** [comment]
Hi Grace, I'll review your code.

**Comment by npnike10** [comment]
So the code is really well-written and I had an easy time getting it to run and understand. The outputs and plots look correct. 

### Positives

- The commenting throughout is great, so is the organization and formatting of outputs and plots on command line during training. 
- The idea of initializing replay buffer without using Q-network is nice. It was fun to think about it and I guess it makes code efficient when we have large NNs and since it's filled with 500 transits, it could fasten training since it decreases correlation in batch data for the first few episodes. 

I also have a few suggestions, which you might be aware of already, and are just nitpicks, but I've included all of them for completeness. 
### Suggestions
- self.capacity attribute isn't really needed in the buffer class. 
- In DQN network definition, arguments to super can be left empty (a change from Python 2 to Python 3). Just super()... can be used instead of super(...,self)... .
- You said the ablation part is under construction anyway, so nothing much to say there but just one thing in case it's useful: DQN functions defined therein are missing init_replay_size argument at the end, in the version I cloned. 
- Lastly, a couple of admin stuff - naming of the PR according to readme and modifying readme to mention whose code you reviewed (this is a new instruction for hw2). 

Overall, great code and I got to learn a few things myself. :D

**Comment by calkins7** [comment]
Thank you for the code review! I appreciate the feedback. To address your comments: 
- I was using the capacity attribute in my buffer class for the initial set up to set the maximum size for the buffer so it deques experiences as the buffer is continuously filled, `self.memory = deque(maxlen=capacity)`. I am not sure how to take out that attribute and still maintain the structure I want, so I left it in for now but in the future I will look over the inputs for carefully!
- I changed the DQN definition to use only `super().__init__()`
- I have updated the ablation study section over the weekend and sorted out all the input parameters. 
- I will make the changes to the README

Thank you for your review!
Grace

**Comment by npnike10** [comment]
Oh yes, the first point’s just that the line  `self.capacity=capacity`
could be removed since the input argument ‘capacity’ is used instead of the class attribute ’self.capacity’ to define maxlen.
 Sorry for the needless confusion.

**Pull request merged**
